#!/usr/bin/env bash
#Install nginx on web-01 server with configuration

sudo apt-get update
sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www/html
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sudo nginx -s reload
