#!/usr/bin/env bash
#Install nginx on web-01 server with configuration

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tree /var/www/html/index.html
sudo service nginx restart
