#!/usr/bin/env bash
#Install nginx on web-01 server with configuration

sudo apt-get update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo nginx -s reload
