#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is
# redirecting to another page.

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tree /var/www/html/index.html
sed -i '/listen 80 default_server/a \\trewrite ^/redirect_me https://devhints.io/bash permanent;\n' /etc/nginx/sites-available/default
sudo service nginx restart
