#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is
# redirecting to another page.

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tree /var/www/html/index.html
sudo sed -i "s#location / {#location /redirect_me {\n\
    \t\trewrite \^/(.*)$ https://devhints.io/bash \
permanent;#g" /etc/nginx/sites-available/default
sudo service nginx restart
