#!/usr/bin/env bash
# install and configure HAproxy on lb-01 server.

sudo apt-get update
sudo apt-get install -y haproxy
echo "echo ENABLED=1 >> /etc/default/haproxy" | sudo bash
sudo sed -i "/defaults/,/option/{s/mode    http/mode   tcp/g}\
" /etc/haproxy/haproxy.cfg
sudo sed -i "/defaults/,/option/{s/option  httplog/option  tcplog/g}\
" /etc/haproxy/haproxy.cfg
echo "
frontend www
    bind    :80
    default_backend web-backend
" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "backend web-backend
    balance roundrobin
    server  448619-web-01 54.152.132.40:80 check
    server  448619-web-02 34.204.81.107:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
