#!/usr/bin/env bash
#onfigures an Ubuntu server with the below requirements.
#Requirements:
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.
#The checker is running on Docker, so make sure to read this
cp /etc/hosts ~/hosts.new
sed -iE "s/^127.0.+localhost$//" ~/hosts.new
echo -e "127.0.0.2\tlocalhost" >> ~/hosts.new
sed -i "s/.* facebook.com$//" ~/hosts.new
echo -e "8.8.8.8\tfacebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
