#!/usr/bin/env bash
# configures the container to fit 
# nginx must be running as nginx user
# nginx must be listening on all active IPs on port 8080
# You cannot use apt-get remove

chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx sed -i "s/listen 80 default_server/listen 8080 default_server/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx start
