#!/usr/bin/env bash
# configures the container to fit - nginx must be running as nginx user - nginx must be listening on all active IPs on port 8080 - You cannot use apt-get remove
chmod u=rw,go=r /etc/nginx/nginx.conf
service apache2 stop
sudo -u nginx sed -i "s/80 /8080/g" /etc/nginx/sites-available/default
sudo -u nginx /etc/init.d/nginx start
