#!/usr/bin/env bash
#  script to reload Gunicorn in a graceful way.

# Send the SIGHUP signal to the Gunicorn master process to gracefully reload
if sudo ps aux | grep gunicorn | grep -v 'grep' | awk '{ print $2 }' | xargs kill -HUP; then
echo "Gunicorn reloaded successfully."
else
echo "Failed to reload Gunicorn." && exit 1
fi